"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

type Theme = "dark" | "light";
type Language = "en" | "ar";

type AppSettingsContextValue = {
  theme: Theme;
  language: Language;
  isArabic: boolean;
  toggleTheme: () => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    howItWorks: "How it Works",
    features: "Features",
    scan: "Scan",
    footerDesc: "QRGuard helps users analyze QR codes and links using layered security analysis to prevent phishing and malicious redirects.",
    product: "Product",
    trustSecurity: "Trust & Security",
    privacyFirst: "Privacy-first",
    noLinkExecution: "No link execution",
    sandboxedAnalysis: "Sandboxed analysis",
    rightsReserved: "All rights reserved.",
    login: "Login",
    signUp: "Sign Up",
    getStarted: "Get Started",
    profile: "Profile",

    signInTitle: "Sign in to QRGuard",
    continueWithGoogle: "Continue with Google",
    emailPasswordRequired: "Email and password are required",
    forgotPassword: "Forgot password?",
    createAccount: "Create account",
    password: "Password",
    confirmPassword: "Confirm Password",
    signingIn: "Signing in...",
    signInButton: "Sign In",
    createAccountTitle: "Create your account",
    creatingAccount: "Creating account...",
    resetPasswordTitle: "Reset your password",
    emailAddress: "Email address",
    sendResetLink: "Send reset link",
    sendingResetLink: "Sending reset link...",
    backToSignIn: "Back to sign in",
    resetTokenMissing: "Reset token is missing.",
    passwordMinLong: "Password must be at least 8 characters long.",
    resetInvalid: "Reset link is invalid or expired.",
    resetSuccess: "Password reset successful. Redirecting to sign in...",
    resetting: "Resetting...",
    resetPasswordButton: "Reset password",
    googleInvalidToken: "Invalid token received from Google callback.",
    editUserInfo: "Edit User Information",
    scanQr: "Scan QR",
    logout: "Logout",
    themeDark: "Dark",
    themeLight: "Light",
    language: "AR",
    cancel: "Cancel",
    saveChanges: "Save Changes",
    saving: "Saving...",

    heroBadge: "Threat Intelligence Active",
    heroTitle: "Scan QR codes. Detect threats before you click.",
    heroDesc: "Do not trust blindly. Our advanced AI engine scans QR codes and URLs for phishing, malware, and digital threats in real time.",
    startScanning: "Start Security Scan",
    instantAnalysis: "Instant Analysis",
    instantAnalysisDesc: "Results in milliseconds",
    bankSecurity: "Bank-Grade Security",
    bankSecurityDesc: "Zero-knowledge privacy",

    scanNew: "New Scan",
    scanSubtitle: "Paste a URL or upload a QR image.",
    scanUploadText: "Click or drag QR image",
    scanUploadHint: "JPG, PNG, WEBP",
    scanScanning: "Scanning...",
    scanOr: "OR",
    scanButton: "Start Security Scan",
    scanButtonLoading: "Scanning...",
    scanInvalidUrl: "Please enter a valid URL starting with http or https.",
    scanLoginRequired: "Please login first to scan links.",
    scanFailed: "Scan failed.",
    scanImageInvalid: "Please upload a valid image.",
    scanQrNotDetected: "QR code not detected. Try a clearer image.",
    scanQrFailed: "Failed to read QR code.",
    scanResult: "Scan Result",
    redirects: "Redirects",
    detectedIssues: "Detected Issues",
    aiInsight: "AI Insight",
    virusTotalSummary: "VirusTotal Summary",
    harmless: "Harmless",
    malicious: "Malicious",
    suspicious: "Suspicious",
    undetected: "Undetected",

    howItWorksTitle: "How It Works",
    howItWorksDesc: "QRGuard follows a structured security pipeline that analyzes QR codes and links through multiple layers before the user interacts with them.",
    step: "STEP",
    step1Title: "Scan QR or Import Link",
    step1Desc: "Upload a QR code image or paste a URL. QRGuard safely extracts the destination without executing it.",
    step2Title: "Static Analysis",
    step2Desc: "The link is inspected for suspicious patterns, misleading domains, and known phishing indicators.",
    step3Title: "Dynamic Analysis",
    step3Desc: "The URL is executed in a sandboxed environment to observe redirects and runtime behavior safely.",
    step4Title: "Risk Assessment",
    step4Desc: "QRGuard generates a clear risk score and explanation before the user interacts with the link.",

    featuresTitle: "Security Features",
    featuresDesc: "QRGuard applies a layered security approach to analyze QR codes and links, combining static inspection, dynamic behavior analysis, and threat intelligence.",
    featureCore: "Core",
    featureExtractionTitle: "QR & URL Extraction",
    featureExtractionDesc: "Safely extracts URLs from QR codes or direct input without executing any embedded content.",
    featureStaticBadge: "Static Analysis",
    featureStaticTitle: "Static URL Inspection",
    featureStaticDesc: "Detects suspicious patterns such as deceptive keywords, IP-based URLs, and abnormal domains.",
    featureDynamicBadge: "Dynamic Analysis",
    featureDynamicTitle: "Sandbox Execution",
    featureDynamicDesc: "Executes links in a controlled environment to observe redirects, scripts, and runtime behavior.",
    featureIntelBadge: "Intelligence",
    featureIntelTitle: "Threat Intelligence",
    featureIntelDesc: "Cross-checks URLs against threat databases and indicators of known malicious activity.",
    featureRiskBadge: "Transparency",
    featureRiskTitle: "Risk Scoring & Classification",
    featureRiskDesc: "Produces a clear risk score and classification explaining why a link is safe or dangerous.",
    featureReportsBadge: "User Control",
    featureReportsTitle: "Reports & History",
    featureReportsDesc: "Allows users to review past scans and detailed reports for auditing and decision-making.",

    profileBadge: "Secure Account Settings",
    profileTitleA: "Edit User",
    profileTitleB: "Information",
    profileDesc: "Update your QRGuard account details. Your changes are protected and sent to the API using your JWT token.",
    backToScan: "Back to Scan",
    profileControl: "Profile Control",
    profileControlDesc: "Keep your account data updated and leave password fields empty if you do not want to change your password.",
    jwtProtected: "JWT Protected",
    jwtProtectedDesc: "Requests use your saved login token.",
    optionalPassword: "Optional Password Update",
    optionalPasswordDesc: "Only filled password fields will be submitted.",
    accountDetails: "Account Details",
    accountDetailsDesc: "Change your public and login information.",
    loadingUser: "Loading user information...",
    username: "Username",
    email: "Email",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    enterUsername: "Enter username",
    enterEmail: "Enter email",
    leavePassword: "Leave empty to keep old password",
    confirmPasswordPlaceholder: "Confirm new password",
    loginRequiredTitle: "Login required",
    loginRequiredDesc: "Please sign in before editing your QRGuard profile information.",
    goToLogin: "Go to Login",
    mustLoginFirst: "You must login first.",
    usernameEmailRequired: "Username and email are required.",
    passwordLength: "Password must be at least 8 characters.",
    passwordsNotMatch: "Passwords do not match.",
    profileUpdated: "Profile updated successfully.",
    loadUserFailed: "Failed to load user data",
    updateProfileFailed: "Failed to update profile",

    dangerTitle: "QR Codes Are Not Always Safe",
    dangerDesc: "QR codes are widely used for payments, menus, and access links, but they can silently redirect users to malicious websites without any visible warning.",
    danger1Title: "Hidden Destinations",
    danger1Desc: "QR codes hide the actual URL, so users cannot preview where the link leads before scanning.",
    danger2Title: "Easy to Manipulate",
    danger2Desc: "Attackers can replace or overlay legitimate QR codes in public places with malicious ones.",
    danger3Title: "High User Trust",
    danger3Desc: "People trust QR codes by default, which makes them a powerful vector for phishing attacks.",
  },
  ar: {
    home: "الرئيسية",
    howItWorks: "طريقة العمل",
    features: "المميزات",
    scan: "الفحص",
    footerDesc: "يساعد QRGuard المستخدمين على تحليل رموز QR والروابط باستخدام تحليل أمني متعدد الطبقات للحد من التصيد والروابط الخبيثة.",
    product: "المنتج",
    trustSecurity: "الثقة والأمان",
    privacyFirst: "الخصوصية أولًا",
    noLinkExecution: "لا يتم تنفيذ أي رابط مباشرة",
    sandboxedAnalysis: "تحليل في بيئة معزولة",
    rightsReserved: "جميع الحقوق محفوظة.",
    login: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    getStarted: "ابدأ الآن",
    profile: "الحساب",

    signInTitle: "تسجيل الدخول إلى QRGuard",
    continueWithGoogle: "المتابعة باستخدام Google",
    emailPasswordRequired: "البريد الإلكتروني وكلمة المرور مطلوبان",
    forgotPassword: "نسيت كلمة المرور؟",
    createAccount: "إنشاء حساب",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    signingIn: "جاري تسجيل الدخول...",
    signInButton: "تسجيل الدخول",
    createAccountTitle: "إنشاء حساب جديد",
    creatingAccount: "جاري إنشاء الحساب...",
    resetPasswordTitle: "إعادة تعيين كلمة المرور",
    emailAddress: "البريد الإلكتروني",
    sendResetLink: "إرسال رابط إعادة التعيين",
    sendingResetLink: "جاري إرسال الرابط...",
    backToSignIn: "العودة إلى تسجيل الدخول",
    resetTokenMissing: "رمز إعادة التعيين غير موجود.",
    passwordMinLong: "كلمة المرور يجب أن تكون 8 أحرف على الأقل.",
    resetInvalid: "رابط إعادة التعيين غير صحيح أو منتهي الصلاحية.",
    resetSuccess: "تم تغيير كلمة المرور بنجاح. سيتم تحويلك إلى تسجيل الدخول...",
    resetting: "جاري إعادة التعيين...",
    resetPasswordButton: "إعادة تعيين كلمة المرور",
    googleInvalidToken: "تم استلام رمز غير صحيح من Google.",
    editUserInfo: "تعديل بيانات المستخدم",
    scanQr: "فحص QR",
    logout: "تسجيل الخروج",
    themeDark: "داكن",
    themeLight: "فاتح",
    language: "EN",
    cancel: "إلغاء",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",

    heroBadge: "معلومات التهديدات مفعلة",
    heroTitle: "افحص رموز QR. اكتشف التهديدات قبل النقر.",
    heroDesc: "لا تثق بشكل أعمى. يقوم محرك الذكاء الاصطناعي المتقدم بفحص رموز QR والروابط لاكتشاف التصيد والبرمجيات الضارة والتهديدات الرقمية في الوقت الحقيقي.",
    startScanning: "ابدأ الفحص الأمني",
    instantAnalysis: "تحليل فوري",
    instantAnalysisDesc: "نتائج في أجزاء من الثانية",
    bankSecurity: "أمان على مستوى البنوك",
    bankSecurityDesc: "خصوصية محمية بالكامل",

    scanNew: "فحص جديد",
    scanSubtitle: "الصق رابطًا أو ارفع صورة QR.",
    scanUploadText: "اضغط أو اسحب صورة QR هنا",
    scanUploadHint: "JPG, PNG, WEBP",
    scanScanning: "جاري الفحص...",
    scanOr: "أو",
    scanButton: "ابدأ الفحص الأمني",
    scanButtonLoading: "جاري الفحص...",
    scanInvalidUrl: "من فضلك أدخل رابطًا صحيحًا يبدأ بـ http أو https.",
    scanLoginRequired: "من فضلك سجل الدخول أولًا لفحص الروابط.",
    scanFailed: "فشل الفحص.",
    scanImageInvalid: "من فضلك ارفع صورة صحيحة.",
    scanQrNotDetected: "لم يتم اكتشاف رمز QR. جرّب صورة أوضح.",
    scanQrFailed: "فشل قراءة رمز QR.",
    scanResult: "نتيجة الفحص",
    redirects: "التحويلات",
    detectedIssues: "المشاكل المكتشفة",
    aiInsight: "تحليل الذكاء الاصطناعي",
    virusTotalSummary: "ملخص VirusTotal",
    harmless: "غير ضار",
    malicious: "ضار",
    suspicious: "مشبوه",
    undetected: "غير مكتشف",

    howItWorksTitle: "كيف يعمل النظام",
    howItWorksDesc: "يتبع QRGuard مسارًا أمنيًا منظمًا لتحليل رموز QR والروابط عبر أكثر من طبقة قبل أن يتفاعل المستخدم معها.",
    step: "الخطوة",
    step1Title: "فحص QR أو إدخال رابط",
    step1Desc: "ارفع صورة رمز QR أو الصق رابطًا. يقوم QRGuard باستخراج الوجهة بأمان بدون تشغيلها.",
    step2Title: "التحليل الثابت",
    step2Desc: "يتم فحص الرابط لاكتشاف الأنماط المشبوهة والدومينات المضللة ومؤشرات التصيد المعروفة.",
    step3Title: "التحليل الديناميكي",
    step3Desc: "يتم تشغيل الرابط داخل بيئة معزولة لمراقبة التحويلات والسلوك أثناء التشغيل بأمان.",
    step4Title: "تقييم الخطورة",
    step4Desc: "يعرض QRGuard درجة خطورة واضحة وشرحًا للنتيجة قبل أن يفتح المستخدم الرابط.",

    featuresTitle: "مميزات الحماية",
    featuresDesc: "يستخدم QRGuard أسلوب حماية متعدد الطبقات لتحليل رموز QR والروابط من خلال الفحص الثابت والتحليل الديناميكي ومعلومات التهديدات.",
    featureCore: "أساسي",
    featureExtractionTitle: "استخراج QR والرابط",
    featureExtractionDesc: "يستخرج الروابط من رموز QR أو من الإدخال المباشر بأمان بدون تشغيل أي محتوى مخفي.",
    featureStaticBadge: "تحليل ثابت",
    featureStaticTitle: "فحص الرابط الثابت",
    featureStaticDesc: "يكتشف الأنماط المشبوهة مثل الكلمات الخادعة والروابط المبنية على IP والدومينات غير الطبيعية.",
    featureDynamicBadge: "تحليل ديناميكي",
    featureDynamicTitle: "تشغيل داخل بيئة معزولة",
    featureDynamicDesc: "يشغّل الروابط داخل بيئة آمنة لمراقبة التحويلات والسكريبتات والسلوك أثناء التشغيل.",
    featureIntelBadge: "معلومات التهديدات",
    featureIntelTitle: "Threat Intelligence",
    featureIntelDesc: "يقارن الروابط مع قواعد بيانات التهديدات ومؤشرات النشاط الضار المعروف.",
    featureRiskBadge: "شفافية",
    featureRiskTitle: "درجة الخطورة والتصنيف",
    featureRiskDesc: "ينتج درجة خطورة واضحة وتصنيفًا يشرح لماذا الرابط آمن أو خطر.",
    featureReportsBadge: "تحكم المستخدم",
    featureReportsTitle: "التقارير والسجل",
    featureReportsDesc: "يسمح للمستخدم بمراجعة عمليات الفحص السابقة والتقارير التفصيلية للمراجعة واتخاذ القرار.",

    profileBadge: "إعدادات الحساب الآمنة",
    profileTitleA: "تعديل بيانات",
    profileTitleB: "المستخدم",
    profileDesc: "قم بتحديث بيانات حسابك في QRGuard. جميع التغييرات محمية ويتم إرسالها إلى API باستخدام رمز JWT الخاص بك.",
    backToScan: "العودة إلى الفحص",
    profileControl: "إعدادات الحماية",
    profileControlDesc: "حافظ على أمان حسابك وتأكد من تحديث بياناتك باستمرار. اترك حقول كلمة المرور فارغة إذا كنت لا تريد تغييرها.",
    jwtProtected: "حماية بواسطة رمز JWT",
    jwtProtectedDesc: "يتم استخدام رمز تسجيل الدخول المحفوظ في متصفحك لإرسال الطلبات.",
    optionalPassword: "تحديث كلمة المرور اختياري",
    optionalPasswordDesc: "سيتم تحديث كلمة المرور فقط إذا تم ملء جميع الحقول.",
    accountDetails: "تفاصيل الحساب",
    accountDetailsDesc: "قم بتغيير معلوماتك العامة وبيانات تسجيل الدخول.",
    loadingUser: "جاري تحميل بيانات المستخدم...",
    username: "اسم المستخدم",
    email: "البريد الإلكتروني",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    enterUsername: "أدخل اسم المستخدم",
    enterEmail: "أدخل البريد الإلكتروني",
    leavePassword: "اتركه فارغًا للإبقاء على كلمة المرور القديمة",
    confirmPasswordPlaceholder: "أعد إدخال كلمة المرور الجديدة",
    loginRequiredTitle: "تسجيل الدخول مطلوب",
    loginRequiredDesc: "من فضلك سجل الدخول قبل تعديل بيانات حسابك في QRGuard.",
    goToLogin: "اذهب إلى تسجيل الدخول",
    mustLoginFirst: "يجب تسجيل الدخول أولًا.",
    usernameEmailRequired: "اسم المستخدم والبريد الإلكتروني مطلوبان.",
    passwordLength: "كلمة المرور يجب أن تكون 8 أحرف على الأقل.",
    passwordsNotMatch: "كلمتا المرور غير متطابقتين.",
    profileUpdated: "تم تحديث البيانات بنجاح.",
    loadUserFailed: "فشل تحميل بيانات المستخدم",
    updateProfileFailed: "فشل تحديث البيانات",

    dangerTitle: "رموز QR ليست آمنة دائمًا",
    dangerDesc: "تُستخدم رموز QR في الدفع والقوائم والروابط، لكنها قد تحوّل المستخدم بصمت إلى مواقع ضارة بدون أي تحذير واضح.",
    danger1Title: "وجهات مخفية",
    danger1Desc: "رموز QR تخفي الرابط الحقيقي، لذلك لا يستطيع المستخدم معرفة الوجهة قبل الفحص.",
    danger2Title: "سهلة التلاعب",
    danger2Desc: "يمكن للمهاجمين استبدال رموز QR الحقيقية أو تغطيتها برموز خبيثة في الأماكن العامة.",
    danger3Title: "ثقة عالية من المستخدمين",
    danger3Desc: "غالبًا يثق الناس في رموز QR تلقائيًا، مما يجعلها وسيلة قوية لهجمات التصيد.",
  },
};

const AppSettingsContext = createContext<AppSettingsContextValue | null>(null);

export function AppSettingsProvider({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState<Theme>("dark");
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedTheme = localStorage.getItem("qrguard_theme") as Theme | null;
    const savedLanguage = localStorage.getItem("qrguard_language") as Language | null;
    if (savedTheme === "dark" || savedTheme === "light") setTheme(savedTheme);
    if (savedLanguage === "en" || savedLanguage === "ar") setLanguage(savedLanguage);
  }, []);

  useEffect(() => {
    localStorage.setItem("qrguard_theme", theme);
    document.documentElement.classList.toggle("light-mode", theme === "light");
    document.documentElement.classList.toggle("dark-mode", theme === "dark");
  }, [theme]);

  useEffect(() => {
    localStorage.setItem("qrguard_language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo<AppSettingsContextValue>(
    () => ({
      theme,
      language,
      isArabic: language === "ar",
      toggleTheme: () => setTheme((current) => (current === "dark" ? "light" : "dark")),
      toggleLanguage: () => setLanguage((current) => (current === "en" ? "ar" : "en")),
      t: (key: string) => translations[language][key] || translations.en[key] || key,
    }),
    [theme, language]
  );

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (!context) throw new Error("useAppSettings must be used inside AppSettingsProvider");
  return context;
}
